/* Bioelements bundle - generated by scripts/bundle-js.js. Do not edit directly. */

/* ===== toctoc.min.js ===== */
!function(h){h.toctoc=function(o){var e=h.extend({headBackgroundColor:"#1c1c1c",headTextColor:"#fff",headLinkColor:"#add8e6",bodyBackgroundColor:"#f5f5f5",bodyLinkColor:"#000",borderStyle:"solid",borderColor:"#000",borderWidth:"2px",headText:"Table of contents",headLinkText:["show","close"],opened:!1,target:"body",smooth:!0},o);const t=h("#toctoc"),r=h("<div></div>").attr("id","toctoc-head"),d=h("<a></a>").attr("href","#"),a=h("<span></span>").text(e.headText),c=h("<div></div>").attr("id","toctoc-body");r.append(a).append(d);o=e.target+" h2, "+e.target+" h3, "+e.target+" h4, "+e.target+" h5, "+e.target+" h6";function n(){e.opened?(d.text(e.headLinkText[1]),c.removeAttr("hidden")):(d.text(e.headLinkText[0]),c.attr("hidden",""))}e.smooth&&h(e.target).addClass("smooth-scroll"),h(o).each(function(o){var e=h(this).prop("tagName").toLowerCase(),t=h(this).text(),o="toctoc-"+(o+1);h(this).attr("id",o),c.append("<a href='#"+o+"'><p class='link link-"+e+"'>"+t+"</p></a>")}),t.append(r.css({"background-color":e.headBackgroundColor,color:e.headTextColor})).append(c.css({"background-color":e.bodyBackgroundColor,"border-style":e.borderStyle,"border-color":e.borderColor,"border-width":e.borderWidth})),d.css({color:e.headLinkColor}),h("#toctoc-body a").css({color:e.bodyLinkColor}),n(),d.on("click",o=>{o.preventDefault(),e.opened?e.opened=!1:e.opened=!0,n()})}}(jQuery);

/* ===== bio-home.js ===== */
(function () {
    function initMobileNav() {
        var header = document.querySelector('.site-header');
        var panel = document.querySelector('[data-nav-panel]');
        var toggler = document.querySelector('[data-nav-toggle]');
        var overlay = document.querySelector('[data-nav-overlay]');
        if (!header || !panel || !toggler) return;

        var mobileQuery = window.matchMedia('(max-width: 991px)');

        function closeMenu() {
            header.classList.remove('is-menu-open');
            document.body.classList.remove('is-nav-open');
            panel.classList.remove('is-open');
            if (overlay) overlay.hidden = true;
        }

        toggler.addEventListener('click', function (e) {
            if (!mobileQuery.matches) return;
            e.preventDefault();

            var open = !panel.classList.contains('is-open');
            header.classList.toggle('is-menu-open', open);
            document.body.classList.toggle('is-nav-open', open);
            panel.classList.toggle('is-open', open);
            if (overlay) overlay.hidden = !open;
        });

        if (overlay) {
            overlay.addEventListener('click', closeMenu);
        }

        document.addEventListener('keyup', function (e) {
            if (e.key === 'Escape') closeMenu();
        });

        mobileQuery.addEventListener('change', function () {
            if (!mobileQuery.matches) closeMenu();
        });
    }

    function initStickyHeader() {
        var header = document.querySelector('.site-header');
        if (!header) return;

        function onScroll() {
            header.classList.toggle('is-scrolled', window.scrollY > 8);
        }

        onScroll();
        window.addEventListener('scroll', onScroll, { passive: true });
    }

    function initTherapyTabs() {
        var section = document.querySelector('.home-therapies');
        if (!section) return;

        var tabs = section.querySelectorAll('.home-therapies__tab');
        var img = section.querySelector('.home-therapies__featured-img');
        var title = section.querySelector('.home-therapies__featured-title');
        var text = section.querySelector('.home-therapies__featured-text');
        if (!tabs.length || !img || !title || !text) return;

        function setFeaturedImage(nextSrc) {
            if (!nextSrc || img.getAttribute('src') === nextSrc) return;

            img.classList.add('is-swapping');

            window.setTimeout(function () {
                img.src = nextSrc;
                img.classList.remove('is-swapping');
            }, 180);
        }

        function activateTab(tab) {
            if (tab.classList.contains('is-active')) return;

            tabs.forEach(function (item) {
                item.classList.remove('is-active');
            });
            tab.classList.add('is-active');

            if (tab.dataset.image) setFeaturedImage(tab.dataset.image);
            if (tab.dataset.title) {
                title.textContent = tab.dataset.title;
                img.alt = tab.dataset.title;
            }
            if (tab.dataset.text) text.textContent = tab.dataset.text;
        }

        tabs.forEach(function (tab) {
            tab.addEventListener('mouseenter', function () {
                activateTab(tab);
            });

            tab.addEventListener('click', function (e) {
                e.preventDefault();
                activateTab(tab);
            });
        });
    }

    function initBestsellersSlider($) {
        var $section = $('.home-bestsellers');
        var $track = $section.find('.owl-bestsellers');
        var $dots = $section.find('.home-bestsellers__dots');

        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        $track.owlCarousel({
            items: 4,
            margin: 16,
            loop: true,
            rewind: true,
            dots: !!$dots.length,
            dotsContainer: $dots.length ? $dots : false,
            nav: false,
            mouseDrag: true,
            touchDrag: true,
            smartSpeed: 600,
            responsive: {
                0: { items: 1, margin: 16 },
                576: { items: 2, margin: 16 },
                992: { items: 3, margin: 16 },
                1200: { items: 4, margin: 16 }
            }
        });

        var resizeTimer;
        $(window).off('resize.owlBestsellers').on('resize.owlBestsellers', function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(function () {
                $track.trigger('refresh.owl.carousel');
            }, 200);
        });
    }

    function initEssenceSlider($) {
        var $section = $('.home-essence');
        var $track = $section.find('.owl-essence');
        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        var $slides = $track.children('.home-essence__card');
        $track.find('.home-essence__card').not($slides).remove();

        if ($slides.length === 3) {
            $slides.clone().appendTo($track);
        }

        $track.owlCarousel({
            items: 3,
            margin: 30,
            loop: true,
            rewind: true,
            dots: false,
            nav: false,
            mouseDrag: true,
            touchDrag: true,
            pullDrag: true,
            smartSpeed: 600,
            responsive: {
                0: { items: 1, margin: 16 },
                768: { items: 2, margin: 24 },
                1200: { items: 3, margin: 30 }
            }
        });

        $section.find('.home-essence__nav-btn--prev').off('click.owlEssence').on('click.owlEssence', function (e) {
            e.preventDefault();
            $track.trigger('prev.owl.carousel');
        });

        $section.find('.home-essence__nav-btn--next').off('click.owlEssence').on('click.owlEssence', function (e) {
            e.preventDefault();
            $track.trigger('next.owl.carousel');
        });

        var resizeTimer;
        $(window).off('resize.owlEssence').on('resize.owlEssence', function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(function () {
                $track.trigger('refresh.owl.carousel');
            }, 200);
        });
    }

    function initComboSlider($) {
        var $section = $('.home-combo');
        var $track = $section.find('.owl-combo');
        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        var $visualImg = $section.find('.home-combo__visual-img');
        var $visualLabel = $section.find('.home-combo__visual-label');
        var $productName = $section.find('.home-combo__product-name');
        var $productPrice = $section.find('.home-combo__product-price');
        var $slides = $track.children('.home-combo__slide');

        function getRealIndex(e) {
            if (e && e.relatedTarget) {
                return e.relatedTarget.relative(e.relatedTarget.current());
            }

            var carousel = $track.data('owl.carousel');
            if (!carousel) return 0;
            return carousel.relative(carousel.current());
        }

        function setVisualImage(nextSrc, altText) {
            if (!nextSrc || $visualImg.attr('src') === nextSrc) return;

            $visualImg.addClass('is-swapping');

            window.setTimeout(function () {
                $visualImg.attr('src', nextSrc);
                if (altText) $visualImg.attr('alt', altText);
                $visualImg.removeClass('is-swapping');
            }, 180);
        }

        function updatePanel(index) {
            var $slide = $slides.eq(index);
            if (!$slide.length) return;

            if ($slide.data('visual')) {
                setVisualImage($slide.data('visual'), $slide.data('label') || '');
            }
            if ($slide.data('label')) $visualLabel.text($slide.data('label'));
            if ($slide.data('name')) $productName.text($slide.data('name'));
            if ($slide.data('price')) $productPrice.find('strong').text($slide.data('price'));
            if ($slide.data('price-old')) $productPrice.find('span').text($slide.data('price-old'));
        }

        $track.owlCarousel({
            items: 1,
            loop: true,
            rewind: true,
            dots: false,
            nav: false,
            margin: 0,
            smartSpeed: 600,
            mouseDrag: true,
            touchDrag: true
        });

        $track.on('initialized.owl.carousel changed.owl.carousel', function (e) {
            updatePanel(getRealIndex(e));
        });

        $section.find('.home-combo__nav-btn--prev').off('click.owlCombo').on('click.owlCombo', function (e) {
            e.preventDefault();
            $track.trigger('prev.owl.carousel');
        });

        $section.find('.home-combo__nav-btn--next').off('click.owlCombo').on('click.owlCombo', function (e) {
            e.preventDefault();
            $track.trigger('next.owl.carousel');
        });
    }

    function initBlogSlider($) {
        var $section = $('.home-blog');
        var $track = $section.find('.owl-blog');
        var $dots = $section.find('.home-blog__dots');

        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        $track.owlCarousel({
            items: 3,
            margin: 30,
            loop: true,
            rewind: true,
            dots: !!$dots.length,
            dotsContainer: $dots.length ? $dots : false,
            nav: false,
            mouseDrag: true,
            touchDrag: true,
            smartSpeed: 600,
            responsive: {
                0: { items: 1, margin: 16 },
                768: { items: 2, margin: 24 },
                1200: { items: 3, margin: 30 }
            }
        });

        var resizeTimer;
        $(window).off('resize.owlBlog').on('resize.owlBlog', function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(function () {
                $track.trigger('refresh.owl.carousel');
            }, 200);
        });
    }

    function initResultsSlider($) {
        var $section = $('.home-results');
        var $track = $section.find('.owl-results');
        var $dots = $section.find('.home-results__dots');
    
        if (!$track.length || !$.fn.owlCarousel) return;
    
        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.find('.owl-stage-outer').children().unwrap();
            $track.removeClass('owl-loaded');
        }
    
        var slideCount = $track.children('.ba-card').length;
    
        $track.owlCarousel({
            items: 3,
            margin: 30,
            loop: slideCount > 3,
            dots: $dots.length > 0,
            dotsContainer: $dots.length ? $dots : false,
            nav: false,
            smartSpeed: 600,
            responsive: {
                0: {
                    items: 1,
                    margin: 16
                },
                768: {
                    items: 2,
                    margin: 24
                },
                1200: {
                    items: 3,
                    margin: 30
                }
            }
        });
    }
    function initCounters() {
        var counters = Array.prototype.slice.call(
            document.querySelectorAll('[data-counter]')
        );
        if (!counters.length) return;

        function runCounter(el) {
            var target = parseFloat(el.getAttribute('data-counter')) || 0;
            var prefix = el.getAttribute('data-counter-prefix') || '';
            var suffix = el.getAttribute('data-counter-suffix') || '';
            var duration = parseInt(el.getAttribute('data-counter-duration'), 10) || 2000;
            var decimals = (String(target).split('.')[1] || '').length;
            var start = null;

            function format(value) {
                return prefix + value.toFixed(decimals) + suffix;
            }

            function step(timestamp) {
                if (start === null) start = timestamp;
                var progress = Math.min((timestamp - start) / duration, 1);
                var eased = 1 - Math.pow(1 - progress, 3);
                el.textContent = format(target * eased);
                if (progress < 1) {
                    window.requestAnimationFrame(step);
                } else {
                    el.textContent = format(target);
                }
            }

            el.textContent = format(0);
            window.requestAnimationFrame(step);
        }

        if (!('IntersectionObserver' in window)) {
            counters.forEach(runCounter);
            return;
        }

        var observer = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (!entry.isIntersecting) return;
                runCounter(entry.target);
                observer.unobserve(entry.target);
            });
        }, { threshold: 0.4 });

        counters.forEach(function (el) {
            observer.observe(el);
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        initMobileNav();
        initStickyHeader();
        initTherapyTabs();
        initCounters();
    });

    window.jQuery(function ($) {
        initEssenceSlider($);
        initBestsellersSlider($);
        initComboSlider($);
        initBlogSlider($);
        initResultsSlider($);
    });
})();

/* ===== bio-guide.js ===== */
(function () {
    function initChips() {
        var wrap = document.querySelector('[data-guide-chips]');
        if (!wrap) return;

        wrap.addEventListener('click', function (event) {
            var chip = event.target.closest('[data-guide-chip]');
            if (!chip) return;

            Array.prototype.forEach.call(wrap.querySelectorAll('[data-guide-chip]'), function (item) {
                item.classList.remove('is-active');
            });
            chip.classList.add('is-active');
        });
    }

    function initPromoSlider($) {
        var $section = $('.guide-promo');
        var $track = $section.find('.owl-guide-promo');
        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        $track.owlCarousel({
            items: 4,
            margin: 16,
            loop: true,
            rewind: true,
            dots: false,
            nav: false,
            mouseDrag: true,
            touchDrag: true,
            smartSpeed: 600,
            responsive: {
                0: { items: 1, margin: 12 },
                576: { items: 2, margin: 12 },
                992: { items: 3, margin: 16 },
                1200: { items: 4, margin: 16 }
            }
        });

        $section.find('[data-guide-promo-prev]').on('click', function (e) {
            e.preventDefault();
            $track.trigger('prev.owl.carousel');
        });

        $section.find('[data-guide-promo-next]').on('click', function (e) {
            e.preventDefault();
            $track.trigger('next.owl.carousel');
        });
    }

    function initToc($) {
        var $toc = $('#toctoc');
        if (!$toc.length || !$.toctoc) return;

        var target = '[data-post-toc-source]';
        if (!document.querySelector(target)) {
            target = '[data-guide-toc-source]';
        }
        if (!document.querySelector(target)) return;

        $.toctoc({
            target: target,
            headText: 'Mục lục',
            headLinkText: ['', ''],
            opened: true,
            smooth: true,
            headBackgroundColor: 'transparent',
            headTextColor: '#020d12',
            headLinkColor: 'transparent',
            bodyBackgroundColor: 'transparent',
            bodyLinkColor: '#6f767c',
            borderStyle: 'none',
            borderColor: 'transparent',
            borderWidth: '0'
        });

        initTocScrollSpy();
    }

    function initPostRelatedSlider($) {
        var $section = $('.post-related');
        var $track = $section.find('.owl-post-related');
        var $dots = $section.find('.post-related__dots');

        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        $track.owlCarousel({
            items: 3,
            margin: 30,
            loop: true,
            rewind: true,
            dots: !!$dots.length,
            dotsContainer: $dots.length ? $dots : false,
            nav: false,
            mouseDrag: true,
            touchDrag: true,
            smartSpeed: 600,
            responsive: {
                0: { items: 1, margin: 16 },
                768: { items: 2, margin: 24 },
                1200: { items: 3, margin: 30 }
            }
        });
    }

    function initCommentLikes() {
        document.addEventListener('click', function (event) {
            var btn = event.target.closest('[data-comment-like]');
            if (!btn) return;

            btn.classList.toggle('is-active');
            var icon = btn.querySelector('i');
            if (!icon) return;

            if (btn.classList.contains('is-active')) {
                icon.classList.remove('fa-regular');
                icon.classList.add('fa-solid');
            } else {
                icon.classList.remove('fa-solid');
                icon.classList.add('fa-regular');
            }
        });
    }

    function initTocScrollSpy() {
        var links = Array.prototype.slice.call(
            document.querySelectorAll('#toctoc-body a')
        );
        if (!links.length) return;

        var targets = links
            .map(function (link) {
                var id = (link.getAttribute('href') || '').slice(1);
                var section = id ? document.getElementById(id) : null;
                return section ? { link: link, section: section } : null;
            })
            .filter(Boolean);
        if (!targets.length) return;

        function setActive(activeLink) {
            links.forEach(function (link) {
                link.classList.toggle('is-active', link === activeLink);
            });
        }

        function onScroll() {
            var offset = 140;
            var current = targets[0];
            for (var i = 0; i < targets.length; i++) {
                if (targets[i].section.getBoundingClientRect().top - offset <= 0) {
                    current = targets[i];
                } else {
                    break;
                }
            }
            setActive(current.link);
        }

        links.forEach(function (link) {
            link.addEventListener('click', function () {
                setActive(link);
            });
        });

        window.addEventListener('scroll', onScroll, { passive: true });
        onScroll();
    }

    initChips();
    initCommentLikes();

    if (window.jQuery) {
        window.jQuery(function () {
            initPromoSlider(window.jQuery);
            initToc(window.jQuery);
            initPostRelatedSlider(window.jQuery);
        });
    }
})();

/* ===== bio-about.js ===== */
(function () {
    function initPartnersLogosMarquee($) {
        var $track = $('.about-partners__logos-track');
        var $group = $track.children('.about-partners__logos-group').first();

        if (!$group.length || $track.children('.about-partners__logos-group').length > 1) return;

        $group.clone(false).attr('aria-hidden', 'true').appendTo($track);
    }

    function initPartnersSlider($) {
        var $slider = $('.about-partners__slider');
        var $track = $slider.find('.owl-about-cases');
        var $dots = $slider.find('.about-partners__dots');

        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        $track.owlCarousel({
            items: 3,
            margin: 30,
            slideBy: 1,
            loop: false,
            rewind: true,
            dots: !!$dots.length,
            dotsContainer: $dots.length ? $dots : false,
            nav: false,
            mouseDrag: true,
            touchDrag: true,
            smartSpeed: 600,
            responsive: {
                0: { items: 1, margin: 16 },
                768: { items: 2, margin: 24 },
                992: { items: 3, margin: 30 }
            }
        });
    }

    window.jQuery(function ($) {
        initPartnersLogosMarquee($);
        initPartnersSlider($);
    });
})();

/* ===== bio-catalog.js ===== */
(function () {
    function formatNumber(value) {
        return Number(value || 0).toLocaleString('vi-VN');
    }

    function initFilterPanel() {
        var panel = document.querySelector('[data-filter-panel]');
        var overlay = document.querySelector('[data-filter-overlay]');
        var openBtn = document.querySelector('[data-filter-open]');
        var closeBtn = document.querySelector('[data-filter-close]');
        var applyBtn = document.querySelector('[data-filter-apply]');
        var clearAllBtn = document.querySelector('[data-filter-clear-all]');
        var clearSelectedBtn = document.querySelector('[data-filter-clear-group="selected"]');
        var countBadge = document.querySelector('.catalog-toolbar__filter-count');
        var chipsWrap = document.querySelector('[data-filter-chips]');
        var inputs = Array.prototype.slice.call(document.querySelectorAll('[data-filter-input]'));
        var minInput = document.querySelector('[data-price-min]');
        var maxInput = document.querySelector('[data-price-max]');
        var minLabel = document.querySelector('[data-price-min-label]');
        var maxLabel = document.querySelector('[data-price-max-label]');
        var progress = document.querySelector('[data-price-progress]');
        var isClosing = false;

        if (!panel || !overlay || !openBtn) return;

        function openPanel() {
            if (panel.classList.contains('is-open')) return;
            isClosing = false;
            panel.hidden = false;
            overlay.hidden = false;
            document.body.classList.add('is-nav-open');
            window.requestAnimationFrame(function () {
                panel.classList.add('is-open');
                overlay.classList.add('is-open');
            });
        }

        function closePanel() {
            if (panel.hidden || isClosing) return;
            isClosing = true;
            panel.classList.remove('is-open');
            overlay.classList.remove('is-open');
            document.body.classList.remove('is-nav-open');

            window.setTimeout(function () {
                panel.hidden = true;
                overlay.hidden = true;
                isClosing = false;
            }, 320);
        }

        function updateCount() {
            if (!countBadge) return;
            var selected = inputs.filter(function (input) {
                return input.checked;
            }).length;
            countBadge.textContent = String(selected);
        }

        function buildChip(group, value) {
            var button = document.createElement('button');
            button.type = 'button';
            button.className = 'catalog-filter-panel__chip';
            button.setAttribute('data-filter-remove', group);
            button.setAttribute('data-filter-value', value);
            button.innerHTML = '<span>' + value + '</span><i class="fa-sharp fa-solid fa-xmark"></i>';
            return button;
        }

        function updateChips() {
            if (!chipsWrap) return;
            chipsWrap.innerHTML = '';

            inputs.forEach(function (input) {
                if (!input.checked) return;
                chipsWrap.appendChild(buildChip(input.dataset.filterGroup, input.value));
            });
        }

        function clearAllFilters() {
            inputs.forEach(function (input) {
                input.checked = false;
            });
            if (minInput) minInput.value = minInput.min || 0;
            if (maxInput) maxInput.value = maxInput.max || 5000000;
            updatePriceUI();
            updateCount();
            updateChips();
        }

        function removeChip(group, value) {
            var matched = inputs.find(function (input) {
                return input.dataset.filterGroup === group && input.value === value;
            });
            if (matched) {
                matched.checked = false;
                updateCount();
                updateChips();
            }
        }

        function updatePriceUI() {
            if (!minInput || !maxInput || !minLabel || !maxLabel || !progress) return;

            var min = parseInt(minInput.value, 10);
            var max = parseInt(maxInput.value, 10);
            var rangeMin = parseInt(minInput.min, 10);
            var rangeMax = parseInt(maxInput.max, 10);

            if (min > max) {
                var swap = min;
                min = max;
                max = swap;
            }

            minInput.value = min;
            maxInput.value = max;
            minLabel.textContent = formatNumber(min);
            maxLabel.textContent = formatNumber(max);

            var left = ((min - rangeMin) / (rangeMax - rangeMin)) * 100;
            var right = 100 - (((max - rangeMin) / (rangeMax - rangeMin)) * 100);
            progress.style.left = left + '%';
            progress.style.right = right + '%';
        }

        openBtn.addEventListener('click', openPanel);
        overlay.addEventListener('click', closePanel);
        if (closeBtn) closeBtn.addEventListener('click', closePanel);
        if (applyBtn) applyBtn.addEventListener('click', closePanel);
        if (clearAllBtn) clearAllBtn.addEventListener('click', clearAllFilters);
        if (clearSelectedBtn) {
            clearSelectedBtn.addEventListener('click', function () {
                inputs.forEach(function (input) {
                    input.checked = false;
                });
                updateCount();
                updateChips();
            });
        }

        document.addEventListener('click', function (event) {
            var chip = event.target.closest('[data-filter-remove]');
            var toggle = event.target.closest('[data-filter-section-toggle]');
            if (chip) {
                removeChip(chip.getAttribute('data-filter-remove'), chip.getAttribute('data-filter-value'));
            }
            if (toggle) {
                var group = toggle.closest('.catalog-filter-group');
                if (group) {
                    group.classList.toggle('is-collapsed');
                    var icon = group.querySelector('.catalog-filter-group__icon');
                    if (icon) {
                        icon.textContent = group.classList.contains('is-collapsed') ? '+' : '-';
                    }
                }
            }
        });

        inputs.forEach(function (input) {
            input.addEventListener('change', function () {
                updateCount();
                updateChips();
            });
        });

        if (minInput) {
            minInput.addEventListener('input', function () {
                if (parseInt(minInput.value, 10) > parseInt(maxInput.value, 10)) {
                    minInput.value = maxInput.value;
                }
                updatePriceUI();
            });
        }

        if (maxInput) {
            maxInput.addEventListener('input', function () {
                if (parseInt(maxInput.value, 10) < parseInt(minInput.value, 10)) {
                    maxInput.value = minInput.value;
                }
                updatePriceUI();
            });
        }

        document.addEventListener('keyup', function (event) {
            if (event.key === 'Escape') closePanel();
        });

        updateCount();
        updateChips();
        updatePriceUI();
    }

    document.addEventListener('DOMContentLoaded', initFilterPanel);
})();

/* ===== bio-product.js ===== */
(function () {
    function initGallery() {
        var gallery = document.querySelector('[data-product-gallery]');
        if (!gallery) return;

        var mainImage = gallery.querySelector('[data-product-main-image]');
        var thumbs = Array.prototype.slice.call(gallery.querySelectorAll('[data-product-thumb]'));

        thumbs.forEach(function (thumb) {
            thumb.addEventListener('click', function () {
                var src = thumb.getAttribute('data-src');
                var alt = thumb.getAttribute('data-alt') || '';
                if (!src || !mainImage) return;

                thumbs.forEach(function (item) {
                    item.classList.remove('is-active');
                });
                thumb.classList.add('is-active');
                mainImage.src = src;
                mainImage.alt = alt;
            });
        });
    }

    function initQuantity() {
        var wrap = document.querySelector('[data-product-qty]');
        if (!wrap) return;

        var input = wrap.querySelector('[data-product-qty-input]');
        var minusBtn = wrap.querySelector('[data-product-qty-minus]');
        var plusBtn = wrap.querySelector('[data-product-qty-plus]');
        var min = Number(input.getAttribute('min') || 1);
        var max = Number(input.getAttribute('max') || 99);

        function setValue(next) {
            var value = Math.min(max, Math.max(min, next));
            input.value = String(value);
        }

        minusBtn.addEventListener('click', function () {
            setValue(Number(input.value || min) - 1);
        });

        plusBtn.addEventListener('click', function () {
            setValue(Number(input.value || min) + 1);
        });

        input.addEventListener('change', function () {
            setValue(Number(input.value || min));
        });
    }

    function initSizes() {
        var sizes = document.querySelector('[data-product-sizes]');
        if (!sizes) return;

        sizes.addEventListener('click', function (event) {
            var button = event.target.closest('[data-product-size]');
            if (!button) return;

            Array.prototype.forEach.call(sizes.querySelectorAll('[data-product-size]'), function (item) {
                item.classList.remove('is-active');
            });
            button.classList.add('is-active');
        });
    }

    function initTabs() {
        var tabs = document.querySelector('[data-product-tabs]');
        if (!tabs) return;

        var links = Array.prototype.slice.call(tabs.querySelectorAll('[data-product-tab]'));
        var panels = Array.prototype.slice.call(document.querySelectorAll('[data-product-panel]'));

        links.forEach(function (link) {
            link.addEventListener('click', function () {
                var target = link.getAttribute('data-product-tab');
                if (!target) return;

                links.forEach(function (item) {
                    item.classList.toggle('is-active', item === link);
                });

                panels.forEach(function (panel) {
                    panel.hidden = panel.getAttribute('data-product-panel') !== target;
                });
            });
        });
    }

    initGallery();
    initQuantity();
    initSizes();
    initTabs();

    function initRelatedSlider($) {
        var $section = $('.product-related');
        var $track = $section.find('.owl-product-related');
        var $dots = $section.find('.product-related__dots');

        if (!$track.length || !$.fn.owlCarousel) return;

        if ($track.hasClass('owl-loaded')) {
            $track.trigger('destroy.owl.carousel');
            $track.removeClass('owl-loaded owl-dragging');
        }

        $track.owlCarousel({
            items: 4,
            margin: 30,
            loop: true,
            rewind: true,
            dots: !!$dots.length,
            dotsContainer: $dots.length ? $dots : false,
            nav: false,
            mouseDrag: true,
            touchDrag: true,
            smartSpeed: 600,
            responsive: {
                0: { items: 1, margin: 16 },
                576: { items: 2, margin: 16 },
                992: { items: 3, margin: 24 },
                1200: { items: 4, margin: 30 }
            }
        });

        var resizeTimer;
        $(window).off('resize.owlProductRelated').on('resize.owlProductRelated', function () {
            clearTimeout(resizeTimer);
            resizeTimer = setTimeout(function () {
                $track.trigger('refresh.owl.carousel');
            }, 200);
        });
    }

    if (window.jQuery) {
        window.jQuery(initRelatedSlider.bind(null, window.jQuery));
    }
})();
